export const httpStatus = {
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  EARLY_HINTS: 103,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  IM_USED: 226,
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  SWITCH_PROXY: 306,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  REQUEST_ENTITY_TOO_LARGE: 413,
  REQUEST_URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  REQUESTED_RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
} as const;

export type HttpStatus = (typeof httpStatus)[keyof typeof httpStatus];

export const httpStatusMessage: Record<HttpStatus, string> = {
  100: 'Continue',
  101: 'Switching Protocols',
  102: 'Processing',
  103: 'Early Hints',
  200: 'OK',
  201: 'Created',
  202: 'Accepted',
  203: 'Non-Authoritative Information',
  204: 'No Content',
  205: 'Reset Content',
  206: 'Partial Content',
  207: 'Multi Status',
  208: 'Already Reported',
  226: 'IM Used',
  300: 'Multiple Choices',
  301: 'Moved Permanently',
  302: 'Found',
  303: 'See Other',
  304: 'Not Modified',
  305: 'Use Proxy',
  306: 'Switch Proxy',
  307: 'Temporary Redirect',
  308: 'Permanent Redirect',
  400: 'Bad Request',
  401: 'Unauthorized',
  402: 'Payment Required',
  403: 'Forbidden',
  404: 'Not Found',
  405: 'Method Not Allowed',
  406: 'Not Acceptable',
  407: 'Proxy Authentication Required',
  408: 'Request Time-out',
  409: 'Conflict',
  410: 'Gone',
  411: 'Length Required',
  412: 'Precondition Failed',
  413: 'Request Entity Too Large',
  414: 'Request-URI Too Large',
  415: 'Unsupported Media Type',
  416: 'Requested Range not Satisfiable',
  417: 'Expectation Failed',
  418: "I'm a teapot",
  421: 'Misdirected Request',
  422: 'Unprocessable Entity',
  423: 'Locked',
  424: 'Failed Dependency',
  425: 'Too Early',
  426: 'Upgrade Required',
  428: 'Precondition Required',
  429: 'Too Many Requests',
  431: 'Request Header Fields Too Large',
  451: 'Unavailable For Legal Reasons',
  500: 'Internal Server Error',
  501: 'Not Implemented',
  502: 'Bad Gateway',
  503: 'Service Unavailable',
  504: 'Gateway Time-out',
  505: 'HTTP Version not Supported',
  506: 'Variant Also Negotiates',
  507: 'Insufficient Storage',
  508: 'Loop Detected',
  510: 'Not Extended',
  511: 'Network Authentication Required',
} as const;

export const httpStatusDetailedMessage: Record<HttpStatus, string> = {
  100: 'The server has received the request headers and the client should proceed to send the request body.',
  101: 'The requester has asked the server to switch protocols and the server has agreed to do so.',
  102: 'A WebDAV request may contain many sub-requests involving file operations, requiring a long time to complete the request. This code indicates that the server has received and is processing the request, but no response is available yet.[7] This prevents the client from timing out and assuming the request was lost.',
  103: 'Used to return some response headers before final HTTP message.',
  200: 'Standard response for successful HTTP requests.',
  201: 'The request has been fulfilled, resulting in the creation of a new resource.',
  202: 'The request has been accepted for processing, but the processing has not been completed.',
  203: "The server is a transforming proxy (e.g. a Web accelerator) that received a 200 OK from its origin, but is returning a modified version of the origin's response.",
  204: 'The server successfully processed the request and is not returning any content.',
  205: 'The server successfully processed the request, but is not returning any content. Unlike a 204 response, this response requires that the requester reset the document view.',
  206: 'The server is delivering only part of the resource (byte serving) due to a range header sent by the client.',
  207: 'The message body that follows is by default an XML message and can contain a number of separate response codes, depending on how many sub-requests were made.',
  208: 'The members of a DAV binding have already been enumerated in a preceding part of the (multistatus) response, and are not being included again.',
  226: 'The server has fulfilled a request for the resource, and the response is a representation of the result of one or more instance-manipulations applied to the current instance.',
  300: 'Indicates multiple options for the resource from which the client may choose.',
  301: 'This and all future requests should be directed to the given URI.',
  302: 'This is an example of industry practice contradicting the standard. The HTTP/1.0 specification (RFC 1945) required the client to perform a temporary redirect (the original describing phrase was "Moved Temporarily"), but popular browsers implemented 302 with the functionality of a 303 See Other. Therefore, HTTP/1.1 added status codes 303 and 307 to distinguish between the two behaviours.',
  303: 'The response to the request can be found under another URI using the GET method.',
  304: 'Indicates that the resource has not been modified since the version specified by the request headers If-Modified-Since or If-None-Match.',
  305: 'The requested resource is available only through a proxy, the address for which is provided in the response.',
  306: 'No longer used. Originally meant "Subsequent requests should use the specified proxy.',
  307: 'In this case, the request should be repeated with another URI, however, future requests should still use the original URI.',
  308: 'The request and all future requests should be repeated using another URI.',
  400: 'The server cannot or will not process the request due to an apparent client error.',
  401: 'Similar to 403 Forbidden, but specifically for use when authentication is required and has failed or has not yet been provided.',
  402: 'Reserved for future use. The original intention was that this code might be used as part of some form of digital cash or micropayment scheme, as proposed for example by GNU Taler, but that has not yet happened, and this code is not usually used.',
  403: 'The request was valid, but the server is refusing action.',
  404: 'The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible.',
  405: 'A request method is not supported for the requested resource.',
  406: 'The requested resource is capable of generating only content not acceptable according to the Accept headers sent in the request.',
  407: 'The client must first authenticate itself with the proxy.',
  408: 'The server timed out waiting for the request.',
  409: 'Indicates that the request could not be processed because of conflict in the request, such as an edit conflict between multiple simultaneous updates.',
  410: 'Indicates that the resource requested is no longer available and will not be available again.',
  411: 'The request did not specify the length of its content, which is required by the requested resource.',
  412: 'The server does not meet one of the preconditions that the requester put on the request.',
  413: 'The request is larger than the server is willing or able to process. Previously called "Request Entity Too Large".',
  414: 'The URI provided was too long for the server to process.',
  415: 'The request entity has a media type which the server or resource does not support.',
  416: 'The client has asked for a portion of the file (byte serving), but the server cannot supply that portion.',
  417: 'The server cannot meet the requirements of the Expect request-header field.',
  418: 'Any attempt to brew coffee with a teapot should result in the error code "418 I\'m a teapot". The resulting entity body MAY be short and stout.',
  421: 'The request was directed at a server that is not able to produce a response.',
  422: 'The request was well-formed but was unable to be followed due to semantic errors.',
  423: 'The resource that is being accessed is locked.',
  424: 'The request failed because it depended on another request and that request failed.',
  425: 'The server is unwilling to risk processing a request that might be replayed.',
  426: 'The client should switch to a different protocol such as TLS/1.0, given in the Upgrade header field.',
  428: 'The origin server requires the request to be conditional.',
  429: 'The user has sent too many requests in a given amount of time.',
  431: 'The server is unwilling to process the request because either an individual header field, or all the header fields collectively, are too large.',
  451: 'A server operator has received a legal demand to deny access to a resource or to a set of resources that includes the requested resource.',
  500: 'A generic error message, given when an unexpected condition was encountered and no more specific message is suitable.',
  501: 'The server either does not recognize the request method, or it lacks the ability to fulfil the request. Usually this implies future availability.',
  502: 'The server was acting as a gateway or proxy and received an invalid response from the upstream server.',
  503: 'The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state.',
  504: 'The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.',
  505: 'The server does not support the HTTP protocol version used in the request.',
  506: 'Transparent content negotiation for the request results in a circular reference.',
  507: 'The server is unable to store the representation needed to complete the request.',
  508: 'The server detected an infinite loop while processing the request.',
  510: 'Further extensions to the request are required for the server to fulfil it.',
  511: 'The client needs to authenticate to gain network access. Intended for use by intercepting proxies used to control access to the network.',
} as const;
